# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4eb5a0db9fe0a6cf2036ec188a9e95fa71b9a69fa368b2ae5f5cd338c2d8671e15716dd6e003496a7debeecbcba4196ee92585d6cb03c5c5542226b878f91c9

test:
  secret_key_base: 12d5dc4385b35702946124021407eb47d9aedb8bb7bc7f193612d1e5068f54ec1717447dda307ce20422050061393b21953fb31fa885dfb414c91d15d1bd74be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
